header:
  schema-version: 2.2.0
  last-updated: "2026-02-16"
  last-reviewed: "2026-02-16"
  url: https://github.com/revanite-io/security-insights-action

project:
  name: Security Insights Action
  homepage: https://github.com/revanite-io/security-insights-action
  administrators:
    - name: Jason Meridth
      affiliation: Chainguard
      primary: true
    - name: Eddie Knight
      affiliation: Sonatype
      primary: false
  repositories:
    - name: security-insights-action
      comment: GitHub Action for validating security-insights.yml files against the OSSF Security Insights CUE schema
      url: https://github.com/revanite-io/security-insights-action
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false
    comment: Please open a GitHub issue to report vulnerabilities

repository:
  status: active
  url: https://github.com/revanite-io/security-insights-action
  accepts-change-request: true
  accepts-automated-change-request: true
  core-team:
    - name: Jason Meridth
      affiliation: Chainguard
      primary: true
    - name: Eddie Knight
      affiliation: Sonatype
      primary: false
  license:
    url: https://github.com/revanite-io/security-insights-action/blob/main/LICENSE.md
    expression: Apache-2.0
  security:
    assessments:
      self:
        comment: No self assessment completed
  release:
    automated-pipeline: false
    distribution-points:
      - uri: https://github.com/revanite-io/security-insights-action/releases
        comment: GitHub Release Page
